Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /smtp.mail.yahoo.com:25
Not Found: /smtp.mail.yahoo.com:25
Not Found: /favicon.ico
Not Found: /smtp.mail.yahoo.com:25
Not Found: /smtp.mail.yahoo.com:25
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.izhongsai.com/
Not Found: /http:/www.baidu.com/
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /smtp.mail.yahoo.com:25
Not Found: /favicon.ico
Not Found: /smtp.mail.yahoo.com:25
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /smtp.mail.yahoo.com:25
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /smtp.mail.yahoo.com:25
Not Found: /favicon.ico
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/
Not Found: /
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /smtp.mail.yahoo.com:25
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /smtp.mail.yahoo.com:25
Not Found: /
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/
Not Found: /http:/www.baidu.com/
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /search.yahoo.com:443
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/
Not Found: /favicon.ico
Internal Server Error: /polls/en_xml/
Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/jack/mysite/polls/views.py", line 45, in en_xml
    print(type(len),len, int(len))
ValueError: invalid literal for int() with base 10: ''
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Internal Server Error: /
Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 565, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'mysite.polls'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/template/defaulttags.py", line 501, in render
    current_app=current_app)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 575, in reverse
    key)
django.core.urlresolvers.NoReverseMatch: 'mysite.polls' is not a registered namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jack/mysite/polls/views.py", line 14, in index
    return render(request, 'polls/index.html')
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/utils/six.py", line 659, in reraise
    raise value
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
django.core.urlresolvers.NoReverseMatch: Reverse for 'en_xml' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: ['$en_xml/']
Not Found: /favicon.ico
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /favicon.ico
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/119.90.40.16:8090/
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Internal Server Error: /
Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/jack/mysite/mysite/urls.py", line 24, in <module>
    url(r'', include('polls.urls', namespace='polls')),
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/jack/mysite/polls/urls.py", line 2, in <module>
    from . import views
  File "/home/jack/mysite/polls/views.py", line 11, in <module>
    from .en_xml import makeup_xml
  File "/home/jack/mysite/polls/en_xml.py", line 10, in <module>
    from en_xml_detail import *
ImportError: No module named 'en_xml_detail'
Not Found: /http:/www.baidu.com/
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Internal Server Error: /
Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/jack/mysite/mysite/urls.py", line 24, in <module>
    url(r'', include('polls.urls', namespace='polls')),
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/jack/mysite/polls/urls.py", line 2, in <module>
    from . import views
  File "/home/jack/mysite/polls/views.py", line 11, in <module>
    from .en_xml import makeup_xml
  File "/home/jack/mysite/polls/en_xml.py", line 10, in <module>
    from en_xml_detail import *
ImportError: No module named 'en_xml_detail'
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/middleware/common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/jack/mysite/mysite/urls.py", line 24, in <module>
    url(r'', include('polls.urls', namespace='polls')),
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/jack/mysite/polls/urls.py", line 2, in <module>
    from . import views
  File "/home/jack/mysite/polls/views.py", line 11, in <module>
    from .en_xml import makeup_xml
  File "/home/jack/mysite/polls/en_xml.py", line 10, in <module>
    from en_xml_detail import *
ImportError: No module named 'en_xml_detail'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/jack/mysite/mysite/urls.py", line 24, in <module>
    url(r'', include('polls.urls', namespace='polls')),
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/jack/mysite/polls/urls.py", line 2, in <module>
    from . import views
  File "/home/jack/mysite/polls/views.py", line 11, in <module>
    from .en_xml import makeup_xml
  File "/home/jack/mysite/polls/en_xml.py", line 10, in <module>
    from en_xml_detail import *
ImportError: No module named 'en_xml_detail'
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/middleware/common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/jack/mysite/mysite/urls.py", line 24, in <module>
    url(r'', include('polls.urls', namespace='polls')),
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/jack/mysite/polls/urls.py", line 2, in <module>
    from . import views
  File "/home/jack/mysite/polls/views.py", line 11, in <module>
    from .en_xml import makeup_xml
  File "/home/jack/mysite/polls/en_xml.py", line 10, in <module>
    from en_xml_detail import *
ImportError: No module named 'en_xml_detail'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/jack/mysite/mysite/urls.py", line 24, in <module>
    url(r'', include('polls.urls', namespace='polls')),
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/jack/mysite/polls/urls.py", line 2, in <module>
    from . import views
  File "/home/jack/mysite/polls/views.py", line 11, in <module>
    from .en_xml import makeup_xml
  File "/home/jack/mysite/polls/en_xml.py", line 10, in <module>
    from en_xml_detail import *
ImportError: No module named 'en_xml_detail'
Not Found: /http:/www.baidu.com/
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Internal Server Error: /polls/
Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/jack/mysite/mysite/urls.py", line 24, in <module>
    url(r'', include('polls.urls', namespace='polls')),
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/jack/mysite/polls/urls.py", line 2, in <module>
    from . import views
  File "/home/jack/mysite/polls/views.py", line 11, in <module>
    from .en_xml import makeup_xml
  File "/home/jack/mysite/polls/en_xml.py", line 10, in <module>
    from en_xml_detail import *
ImportError: No module named 'en_xml_detail'
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /search.yahoo.com:443
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/119.90.40.16:8090/
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Internal Server Error: /
Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/jack/mysite/mysite/urls.py", line 24, in <module>
    url(r'', include('polls.urls', namespace='polls')),
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/jack/mysite/polls/urls.py", line 2, in <module>
    from . import views
  File "/home/jack/mysite/polls/views.py", line 11, in <module>
    from .en_xml import makeup_xml
  File "/home/jack/mysite/polls/en_xml.py", line 10, in <module>
    from en_xml_detail import *
ImportError: No module named 'en_xml_detail'
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/middleware/common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/jack/mysite/mysite/urls.py", line 24, in <module>
    url(r'', include('polls.urls', namespace='polls')),
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/jack/.pyenv/versions/3.3.4/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/jack/mysite/polls/urls.py", line 2, in <module>
    from . import views
  File "/home/jack/mysite/polls/views.py", line 11, in <module>
    from .en_xml import makeup_xml
  File "/home/jack/mysite/polls/en_xml.py", line 10, in <module>
    from en_xml_detail import *
ImportError: No module named 'en_xml_detail'
Not Found: /favicon.ico
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
